version: '3'
services:
  app:
    container_name: indoor-app
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:latest
